"""users reviews snackbars table

Revision ID: 066235c63512
Revises: 
Create Date: 2025-01-11 15:20:11.784913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066235c63512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('snackbar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snackbar_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_snackbar_user_id'), ['user_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snackbar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snackbar_id'], ['snackbar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_snackbar_id'), ['snackbar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_timestamp'))
        batch_op.drop_index(batch_op.f('ix_review_snackbar_id'))

    op.drop_table('review')
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snackbar_user_id'))
        batch_op.drop_index(batch_op.f('ix_snackbar_name'))

    op.drop_table('snackbar')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
