"""snackbars table

Revision ID: 1a84338eac60
Revises: 066235c63512
Create Date: 2025-01-11 15:25:04.793996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a84338eac60'
down_revision = '066235c63512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=140), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('about')

    # ### end Alembic commands ###
