"""Added is_deleted field to user, snackbar and review

Revision ID: 709174d42bd3
Revises: e038bf090758
Create Date: 2025-01-17 05:24:38.819354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709174d42bd3'
down_revision = 'e038bf090758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
