"""is_genieter nu in de User model

Revision ID: ac3367c9b58c
Revises: baccbee19c8e
Create Date: 2025-01-21 16:00:54.268160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac3367c9b58c'
down_revision = 'baccbee19c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_genieter', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_genieter')

    # ### end Alembic commands ###
