"""reviews snackbars table

Revision ID: b9f4ff048675
Revises: 1453953d44be
Create Date: 2025-01-10 13:01:14.045634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9f4ff048675'
down_revision = '1453953d44be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snackbar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snackbar_user_id'), ['user_id'], unique=False)

    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snackbar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['snackbar_id'], ['snackbar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_snackbar_id'), ['snackbar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_timestamp'))
        batch_op.drop_index(batch_op.f('ix_review_snackbar_id'))

    op.drop_table('review')
    with op.batch_alter_table('snackbar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snackbar_user_id'))

    op.drop_table('snackbar')
    # ### end Alembic commands ###
